version: '3.7'
services:
  php:
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    build:
      context: ./docker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      COMPOSER_HOME: /tmp/composer
      XDEBUG_MODE: ${XDEBUG_MODE}
    depends_on:
      - database

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: yousign
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: gh-archive-keyword
    ports:
      - "8001:5432"

  wiremock:
    image: wiremock/wiremock:2.32.0
    ports:
      - "8086:8080"

  adminer:
    image: adminer:4.7
    links:
      - "database:db"
    ports:
      - "8888:8080"
